DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
        (
        id NUMBER(10) NOT NULL,
        name VARCHAR2(50) NOT NULL,
        PRIMARY KEY(id)
        );
CREATE  TABLE  USER
(
id NUMBER(10) NOT NULL,
        name VARCHAR2(50) NOT NULL,
        PRIMARY KEY(id)
);